const countryOptions = [
    { value: 'US', label: 'US', code: 'US' },
    { value: 'CA', label: 'CA', code: 'CA' },
    { value: 'GB', label: 'GB', code: 'GB' },
    { value: 'AU', label: 'AU', code: 'AU' },
    { value: 'DE', label: 'DE', code: 'DE' },
    { value: 'FR', label: 'FR', code: 'FR' },
    { value: 'JP', label: 'JP', code: 'JP' },
    { value: 'IT', label: 'IT', code: 'IT' },
    { value: 'ES', label: 'ES', code: 'ES' },
    { value: 'NL', label: 'NL', code: 'NL' },
    { value: 'BR', label: 'BR', code: 'BR' },
    { value: 'IN', label: 'IN', code: 'IN' },
    { value: 'CN', label: 'CN', code: 'CN' },
    { value: 'MX', label: 'MX', code: 'MX' },
    { value: 'KR', label: 'SK', code: 'KR' },
    { value: 'SG', label: 'SG', code: 'SG' },
    { value: 'SE', label: 'SE', code: 'SE' },
    { value: 'CH', label: 'CH', code: 'CH' },
    { value: 'DK', label: 'Dk', code: 'DK' },
    { value: 'NO', label: 'NO', code: 'NO' },
    { value: 'FI', label: 'FI', code: 'FI' },
    { value: 'IE', label: 'IE', code: 'IE' },
    { value: 'AT', label: 'AT', code: 'AT' },
    { value: 'BE', label: 'BE', code: 'BE' },
    { value: 'NZ', label: 'NZ', code: 'NZ' },
    { value: 'PT', label: 'PT', code: 'PT' },
    { value: 'PL', label: 'PL', code: 'PL' },
    { value: 'RU', label: 'RU', code: 'RU' },
    { value: 'ZA', label: 'ZA', code: 'ZA' },
    { value: 'AR', label: 'AR', code: 'AR' },
   
];

  export default countryOptions;